Add MacOS (#9)
* Add lzma dependency for wx's built-in tif support

* Add requests and gettext

requests is used by wxpython builder to download waf tool.

gettext is required for msgfmt, which is used by wx build to rebuild
message catalogs.

* Kill ping loop also in error handler

* remove gettext dependency on Windows

* conda-forge-linter says two spaces before selector

* lint

* corrections after rebase

* updated recipe for new version of wxpython

* MNT: Re-rendered with conda-smithy 2.4.2

* Update .travis.yml

* enabled c++11 support to hopefully resolve the type_traits error

* Update build.sh

* Test and increase macosx-version-min build setting (#4)

With macosx-version-min 10.7 and `-stdlib=libc++` the build would
break with "wx/strvararg.h:25:14: fatal error: 'type_traits' file not
found"

Setting the macosx-version-min to 10.9 fixes this.

* Try without brew cask install xquartz

* MNT: Re-rendered with conda-smithy 2.4.2